# Generated by Django 3.2.4 on 2021-07-04 02:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0002_clases_owner_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestros',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(blank=True, max_length=24, null=True)),
                ('cursos', models.ManyToManyField(related_name='cursos', to='Cursos.Clases')),
            ],
        ),
    ]
